apiVersion: v1
kind: Pod
metadata:
  name: meupod
spec:
  containers:
    - name: web
      image: rrborba/web-page:blue
      ports:
        - containerPort: 80
---

# usando labels
apiVersion: v1
kind: Pod
metadata:
  name: meupod-2
  labels:
    app: green
spec:
  containers:
    - name: web
      image: rrborba/web-page:green
      ports:
        - containerPort: 80
