apiVersion: v1
kind: Pod
metadata:
  nome: meupod
spec:
  containers:
    - name: web
      image: kubedevio/web-page:blue
      ports:
        - containerPort: 80
---

# usando labels
apiVersion: v1
kind: Pod
metadata:
  nome: meusegundopod
  labels:
    app: web
spec:
  containers:
    - name: web
      image: kubedevio/web-page:blue
      ports:
        - containerPort: 80
