name: CI-CD

on:
  push:
    branches: [ main ]


  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }} # usando dados secretos
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Docker build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./Kind-Kubernet/rotten-potatoes-main/src
          file: ./Kind-Kubernet/rotten-potatoes-main/src/Dockerfile
          push: true
          tags: |
            rrborba/rotten-potatoes:latest
            rrborba/rotten-potatoes:${{ github.run_number }}     
        # cria uma var de contagem de versão automatica
        
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
        # não vai funcina pois a variavel não tem conteudo 
        
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          images: rrborba/rotten-potatoes:${{ github.run_number }} 
          manifests: |
            ./Kind-Kubernet/rotten-potatoes-main/k8s/deployment.yaml
            
        
        
        
        
        
        
        
        
        
        
